dist: bionic
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-snapshot
      - libboost-dev
      - libboost-program-options-dev
      - libgtest-dev
      - cmake

before_install:
  - sudo mkdir /usr/src/googletest/googletest/build
  - cd /usr/src/googletest/googletest/build
  - sudo cmake ..
  - sudo make install -j10
  - sudo rm -rf /usr/src/googletest/googletest/build
  - cd -

script:
  - mkdir build
  - cd build
  - CXX=/usr/lib/gcc-snapshot/bin/g++ CC=/usr/lib/gcc-snapshot/bin/gcc cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . -- -j10
  - ./webpptest
